services:
  namenode:
    build:
      context: .
      dockerfile: Dockerfile.namenode
    container_name: namenode
    environment:
      - CLUSTER_NAME=bigdata-cluster
      - HDFS_CONF_dfs_permissions_enabled=false
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HADOOP_USER_NAME=root
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hadoop_namenode:/opt/hadoop/logs
      - ../dataset:/dataset
      - ../scripts:/scripts
    user: root

  datanode:
    build:
      context: .
      dockerfile: Dockerfile.datanode
    container_name: datanode
    environment:
      - CLUSTER_NAME=bigdata-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_permissions_enabled=false
      - HADOOP_USER_NAME=root
    ports:
      - "9864:9864"
    volumes:
      - hadoop_datanode:/opt/hadoop/logs
    user: root
    depends_on:
      - namenode

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    environment:
      - HIVE_METASTORE_DB_TYPE=postgres
      - HIVE_METASTORE_HOST=hive-metastore
      - HIVE_METASTORE_PORT=9083
      - HIVE_METASTORE_USER=hive
      - HIVE_METASTORE_PASSWORD=hive
      - HIVE_METASTORE_DB=hive
      - HIVE_SITE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://hive-metastore-postgresql:5432/hive
      - HIVE_SITE_CONF_javax_jdo_option_ConnectionDriverName=org.postgresql.Driver
      - HIVE_SITE_CONF_javax_jdo_option_ConnectionUserName=hive
      - HIVE_SITE_CONF_javax_jdo_option_ConnectionPassword=hive
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_permissions_enabled=false
    ports:
      - "9083:9083"
    depends_on:
      - namenode
      - datanode
      - hive-metastore-postgresql

  hive-metastore-postgresql:
    image: postgres:13
    container_name: hive-metastore-postgresql
    environment:
      - POSTGRES_DB=hive
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
    ports:
      - "5432:5432"
    volumes:
      - hive_pgdata:/var/lib/postgresql/data

  spark:
    image: bitnami/spark:3.5.1
    container_name: spark
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark
      - SPARK_MASTER_PORT=7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2
      - SPARK_DRIVER_MEMORY=2G
      - SPARK_EXECUTOR_MEMORY=2G
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_permissions_enabled=false
      # Spark Hadoop configurations
      - SPARK_CONF_spark_hadoop_fs_defaultFS=hdfs://namenode:9000
      - SPARK_CONF_spark_hadoop_dfs_client_use_datanode_hostname=true
      - SPARK_CONF_spark_hadoop_dfs_permissions_enabled=false
      - SPARK_CONF_spark_sql_adaptive_enabled=true
      - SPARK_CONF_spark_sql_adaptive_coalescePartitions_enabled=true
      # User settings
      - HADOOP_USER_NAME=root
      - SPARK_USER=root
    ports:
      - "4040:4040"
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ../dataset:/dataset
      - ../scripts:/scripts
    depends_on:
      - namenode
      - datanode
      - hive-metastore-postgresql
    user: root

  spark-worker:
    image: bitnami/spark:3.5.1
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_permissions_enabled=false
      - HADOOP_USER_NAME=root
      - SPARK_USER=root
    volumes:
      - ../dataset:/dataset
      - ../scripts:/scripts
    depends_on:
      - spark
    user: root

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hive_pgdata: